wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32]
    rows: [10, 10, 10]
  refreshInterval: 1
  mods:
    github_prs:
      type: github
      enabled: true
      position:
        top: 0
        left: 0
        height: 2
        width: 2
      refreshInterval: 300
      repositories:
        hirokisakabe/dotfiles: "myPRs"
      apiKey: "${WTF_GITHUB_TOKEN}"
      enableStatus: true
      uploadURL: ""
      baseURL: ""
      username: "hirokisakabe"
    github_review:
      type: github
      enabled: true
      position:
        top: 0
        left: 2
        height: 2
        width: 1
      refreshInterval: 300
      repositories:
        hirokisakabe/dotfiles: "othersPRs"
      customQueries:
        reviewRequests:
          title: "Review Requests"
          filter: "is:open is:pr review-requested:hirokisakabe"
      apiKey: "${WTF_GITHUB_TOKEN}"
      enableStatus: true
      uploadURL: ""
      baseURL: ""
      username: "hirokisakabe"
    git:
      type: git
      enabled: true
      position:
        top: 2
        left: 0
        height: 1
        width: 2
      commitCount: 10
      commitFormat: short
      dateFormat: "Jan 02, 15:04"
      repositories:
        - "${HOME}/work/dotfiles"
    resourceusage:
      type: resourceusage
      enabled: true
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 5
