# Frosted Aqua palette

[mgr]
cwd = { fg = "#4c87c7" }
hovered = { reversed = true }
preview_hovered = { underline = true }
find_keyword = { fg = "#966824", italic = true }
find_position = { fg = "#8076b3", bg = "reset", italic = true }
marker_copied = { fg = "#3f8969", bg = "#3f8969" }
marker_cut = { fg = "#b84f68", bg = "#b84f68" }
marker_marked = { fg = "#378a9b", bg = "#378a9b" }
marker_selected = { fg = "#4c87c7", bg = "#4c87c7" }
tab_active = { fg = "#12283a", bg = "#93d2ea" }
tab_inactive = { fg = "#203b52", bg = "#c7eaf6" }
tab_width = 1
border_symbol = "│"
border_style = { fg = "#8abdd0" }

[mode]
normal_main = { fg = "#12283a", bg = "#93d2ea", bold = true }
normal_alt = { fg = "#4c87c7", bg = "#c7eaf6" }
select_main = { fg = "#12283a", bg = "#b9dfd0", bold = true }
select_alt = { fg = "#3f8969", bg = "#c7eaf6" }
unset_main = { fg = "#12283a", bg = "#cfc9e8", bold = true }
unset_alt = { fg = "#8076b3", bg = "#c7eaf6" }

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#c7eaf6", bg = "#c7eaf6" }
progress_label = { fg = "#203b52", bold = true }
progress_normal = { fg = "#4c87c7", bg = "#c7eaf6" }
progress_error = { fg = "#b84f68", bg = "#c7eaf6" }
permissions_t = { fg = "#4c87c7" }
permissions_r = { fg = "#966824" }
permissions_w = { fg = "#b84f68" }
permissions_x = { fg = "#3f8969" }
permissions_s = { fg = "#6d8496" }

[input]
border = { fg = "#4c87c7" }
title = {}
value = {}
selected = { reversed = true }

[confirm]
border = { fg = "#4c87c7" }
title = { fg = "#4c87c7" }
content = {}
list = {}
btn_yes = { reversed = true }
btn_no = {}
btn_labels = [ "[Y(es)]", "[(N)o]" ]

[pick]
border = { fg = "#4c87c7" }
active = { fg = "#8076b3", bold = true }
inactive = {}

[cmp]
border = { fg = "#4c87c7" }
active = { reversed = true }
inactive = {}
icon_file = ""
icon_folder = ""
icon_command = ""

[tasks]
border = { fg = "#4c87c7" }
title = {}
hovered = { fg = "#8076b3", underline = true }

[which]
mask = { bg = "#c7eaf6" }
cand = { fg = "#378a9b" }
rest = { fg = "#6d8496" }
desc = { fg = "#8076b3" }
separator = "  "
separator_style = { fg = "#6d8496" }

[help]
on = { fg = "#378a9b" }
run = { fg = "#8076b3" }
hovered = { reversed = true, bold = true }
footer = { fg = "#12283a", bg = "#c7eaf6" }

[notify]
title_info = { fg = "#3f8969" }
title_warn = { fg = "#966824" }
title_error = { fg = "#b84f68" }
icon_info = ""
icon_warn = ""
icon_error = ""

[filetype]
rules = [
  { mime = "image/*", fg = "#966824" },
  { mime = "{audio,video}/*", fg = "#8076b3" },
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#b84f68" },
  { mime = "application/{pdf,doc,rtf,*office*}", fg = "#378a9b" },
  { url = "*", fg = "#203b52" },
  { url = "*/", fg = "#4c87c7" },
]
