# Frosted Aqua palette
gui:
  theme:
    activeBorderColor:
      - "#4c87c7"
      - bold
    inactiveBorderColor:
      - "#8abdd0"
    optionsTextColor:
      - "#5e9bd9"
    selectedLineBgColor:
      - "#c7eaf6"
    selectedRangeBgColor:
      - "#b4dfed"
    cherryPickedCommitBgColor:
      - "#b9dfd0"
    cherryPickedCommitFgColor:
      - "#3f8969"
    unstagedChangesColor:
      - "#b84f68"
    defaultFgColor:
      - "#203b52"
  authorColors:
    "*": "#8076b3"
