# Atrium Library palette
gui:
  theme:
    activeBorderColor:
      - "#596166"
      - bold
    inactiveBorderColor:
      - "#cbd1d4"
    optionsTextColor:
      - "#687078"
    selectedLineBgColor:
      - "#dce1e3"
    selectedRangeBgColor:
      - "#cbd1d4"
    cherryPickedCommitBgColor:
      - "#d6e2d6"
    cherryPickedCommitFgColor:
      - "#687768"
    unstagedChangesColor:
      - "#945f5f"
    defaultFgColor:
      - "#1f2326"
  authorColors:
    "*": "#756d7a"
