auto_sync = false
update_check = false

search_mode = "fuzzy"
filter_mode = "global"
workspaces = true

style = "compact"
enter_accept = false
show_preview = true

secrets_filter = true
store_failed = true
