format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""


# Frosted Aqua palette
[directory]
style = "bold #4c87c7"

[character]
success_symbol = "[❯](#3f8969)"
error_symbol = "[❯](#b84f68)"
vimcmd_symbol = "[❮](#8076b3)"

[git_branch]
format = "[$branch]($style)"
style = "bold #5e9bd9"

[git_status]
format = "[(*$conflicted$untracked$modified$staged$renamed$deleted) ($ahead_behind$stashed)]($style)"
conflicted = ""
untracked = ""
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[cmd_duration]
format = "[$duration]($style) "
