format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""


# Iceberg palette
[directory]
style = "bold #84a0c6"

[character]
success_symbol = "[❯](#b4be82)"
error_symbol = "[❯](#e27878)"
vimcmd_symbol = "[❮](#a093c7)"

[git_branch]
format = "[$branch]($style)"
style = "bold #a093c7"

[git_status]
format = "[(*$conflicted$untracked$modified$staged$renamed$deleted) ($ahead_behind$stashed)]($style)"
conflicted = ""
untracked = ""
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[cmd_duration]
format = "[$duration]($style) "
