format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""


# Atrium Library palette
[directory]
style = "bold #41484c"

[character]
success_symbol = "[❯](#1f2326)"
error_symbol = "[❯](#945f5f)"
vimcmd_symbol = "[❮](#596166)"

[git_branch]
format = "[$branch]($style)"
style = "bold #596166"

[git_status]
format = "[(*$conflicted$untracked$modified$staged$renamed$deleted) ($ahead_behind$stashed)]($style)"
conflicted = ""
untracked = ""
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[cmd_duration]
format = "[$duration]($style) "
